
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from '@/app/prisma/models/User'
export type * from '@/app/prisma/models/Course'
export type * from '@/app/prisma/models/Enrollment'
export type * from '@/app/prisma/models/Lesson'
export type * from '@/app/prisma/models/LessonCompleted'
export type * from '@/app/prisma/commonInputTypes'