import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Toast */}
        <ToastContainer />

        {/* OAuth Provider */}
        <SessionProvider>
          {children}
        </SessionProvider>

      </body>
    </html>
  );
}
